spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: abc123
  thymeleaf:
    mode: HTML
    suffix: .html
  servlet:
    multipart:
      enabled: on
      location: E:\upload
      max-file-size: 10MB
server:
  port: 10800

